### PR TITLE
Adds 'rq>0.7' version support

### PR DESCRIPTION
**Pull request by sobolevn**
Changes:
1. Removed 'rq<0.7' part from deps
2. Added new options in `cli` and `script`
3. Added new function to check rq version in `helpers`
4. Added new logic to `worker` command in `cli` and `script`
5. Changed `tox` targets to test both `latest` and `lowest` `rq` versions
6. Fixed some test, which were failing due to `isort`

Refs #12, refs #13

### CODE REVIEW

**Comment by sobolevn** [comment]
Local tests:

>   py27-lowest: commands succeeded
>   py27-latest: commands succeeded
>   py27-devel: commands succeeded
> ERROR:   py34-lowest: InterpreterNotFound: python3.4
> ERROR:   py34-latest: InterpreterNotFound: python3.4
> ERROR:   py34-devel: InterpreterNotFound: python3.4
> ERROR:   py35-lowest: InterpreterNotFound: python3.5
> ERROR:   py35-latest: InterpreterNotFound: python3.5
> ERROR:   py35-devel: InterpreterNotFound: python3.5
>   py36-lowest: commands succeeded
>   py36-latest: commands succeeded
>   py36-devel: commands succeeded
>   docs: commands succeeded
>   readme: commands succeeded
>   manifest: commands succeeded

**Comment by sobolevn** [comment]
That's quite strange. Because when I try to fix these `isort` issues, it starts to fail locally.
What should I do? @jezdez

**Comment by nzjrs** [comment]
Except for the build failures (for isort...) this has been running well for me in production. Any chance to get a release with this fix?

**Comment by asteinlein** [comment]
Any progress on this? Would be much appreciated, as I need to use Flask-RQ2 with rq 0.7.1...

**Comment by sobolevn** [comment]
@asteinlein waiting for the @jezdez review.

**Pull request closed without merging**
